set ruler
" Sintaxis only si tengo colores
if &t_Co >1
	syn on
endif
set modeline
set ls=2
runtime! plugin/**/*.vim
let Tlist_Ctags_Cmd = "/usr/local/bin/ctags"
let Tlist_WinWidth = 50
map <F4> :TlistToggle<cr>
"set list
set listchars=eol:¶,trail:·


"Only if gui version is running
if has("gui_running")
	set number
	map <C-Tab> :bnext<cr>
	map <C-S-Tab> :bprev<cr>
	colors macvim
	"set bg=dark
endif 
au BufRead *.[ch] setlocal ts=2 |
	\ setlocal expandtab |
	\ setlocal cinoptions=l1,t0,(0,u0,w1,W4 
au BufWinEnter *.[ch] setlocal ts=2 |
	\ setlocal expandtab
au BufRead,BufWinEnter *.py setlocal ts=4 |
	\ setlocal expandtab |
	\ setlocal shiftwidth=4|
" Sintaxis only si tengo colores
	\ set listchars=eol:¶
au BufRead,BufWinEnter *.yml setlocal ts=2 |
	\ setlocal expandtab |
	\ setlocal shiftwidth=2|
	
au BufRead,BufWinEnter *.java setlocal ts=4 |
	\ setlocal expandtab |
	\ setlocal shiftwidth=4|

au BufRead,BufWinEnter *.m setlocal ts=4 |
	\ setlocal expandtab |
	\ setlocal shiftwidth=4|
au BufRead,BufWinEnter *.json setlocal ts=4 |
	\ setlocal expandtab |
	\ setlocal shiftwidth=4|

colorscheme darkblue
"highlight ExtraWhitespace ctermbg=red guibg=red
"match  ExtraWhitespace /\s\+$/
